import type { Metadata } from "next";
import "./globals.css";

import { Inter } from "next/font/google";
import Header from "../app/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Permission Manager App",
  description: "Generated by Cristian Daniel Arenas",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="w-full max-w-7xl mt-4 m-auto">{children}</div>
      </body>
    </html>
  );
}
